### ISSUE TITLE
dev-python/nethsm-0.5.0: can't fetch source

### ISSUE THREAD

**Issue by kcning** [jjakob/gentoo-overlay#3]
The upstream has renamed the repo to https://github.com/Nitrokey/nethsm-sdk-py
In addition, version 1.0.0 has been published. Would you mind taking a look? Thank you.

**Comment by jjakob** [comment]
Thanks for the report, I'll make ebuilds for the latest nethsm-sdk-py and pynitrokey.

**Comment by jjakob** [comment]
Should work now. I had a typo in SRC_URI (`$P` instead of `$PN`) but I'll remove nethsm-0.5.0 anyway as 1.0.0 works.

**Comment by kcning** [comment]
Thank you!
