### ISSUE TITLE
app-crypt/pynitrokey: python3.12 support

### ISSUE THREAD

**Issue by kcning** [jjakob/gentoo-overlay#6]
Hello, thank you for maintaining this package! Gentoo is migrating to Python 3.12. Would it be possible to enable it for pynitrokey?

Btw the upstream released a new version a few days ago.

**Comment by jjakob** [comment]
I'm already working on updating all the dependencies to py3.12, should be done in a couple days as I get time to work on it.

**Comment by jjakob** [comment]
I pushed the updates to a staging branch, I tested pynitrokey (interacting with a NK3 works, as does upgrading firmware), I had some test errors in spsdk so I'm waiting what they have to say at https://github.com/nxp-mcuxpresso/spsdk/issues/73 but you can already try and use the staging branch [py3.12_staging_pynitrokey](https://github.com/jjakob/gentoo-overlay/tree/py3.12_staging_pynitrokey)

**Comment by kcning** [comment]
thank you!

**Comment by jjakob** [comment]
test error fixed, merged into master
